COMPILER = gcc

01 : $(OBJS)
	$(COMPILER) menu.c -g3 -w -lSDL2 -lSDL2_image -lSDL2_ttf -o menu.out
	./menu.out
	rm menu.out

02 : $(OBJS)
	$(COMPILER) menu2.c -g3 -w -lSDL2 -lSDL2_image -lSDL2_ttf -o menu2.out
	./menu2.out
	rm menu2.out
	
03 : $(OBJS)
	$(COMPILER) menu3.c -g3 -w -lSDL2 -lSDL2_image -lSDL2_ttf -o menu3.out
	./menu3.out
	rm menu3.out

