COMPILER = gcc

01: $(OBJS)
	$(COMPILER) 01_hello_SDL.c -w -lSDL2 -lSDL2_image  -o 01_hello_SDL.out
	./01_hello_SDL.out
	rm 01_hello_SDL.out

02: $(OBJS)
	$(COMPILER) 02_hello_SDL_PNG_global.c -w -lSDL2 -lSDL2_image -o 02_hello_SDL_PNG.out
	./02_hello_SDL_PNG.out
	rm 02_hello_SDL_PNG.out

03: $(OBJS)
	$(COMPILER) 03_xOutTheWindow_SDL.c -w -lSDL2 -lSDL2_image -o 03_xOutTheWindow.out
	./03_xOutTheWindow.out
	rm 03_xOutTheWindow.out

04: $(OBJS)
	$(COMPILER) 04_keyPresses.c -w -lSDL2 -lSDL2_image -o 04_keyPresses.out
	./04_keyPresses.out
	rm 04_keyPresses.out

05: $(OBJS)
	$(COMPILER) 05_optimizedSurface.c -w -lSDL2 -lSDL2_image -o 05_optimizedSurface.out
	./05_optimizedSurface.out
	rm 05_optimizedSurface.out

06: $(OBJS)
	$(COMPILER) 06_PNG_load.c -w -lSDL2 -lSDL2_image -o 06_PNG_load.out
	./06_PNG_load.out
	rm ./06_PNG_load.out

07: $(OBJS)
	$(COMPILER) 07_RenderingTexture.c -w -lSDL2 -lSDL2_image -o 07_RenderingTexture.out
	./07_RenderingTexture.out
	rm 07_RenderingTexture.out

08: $(OBJS)
	$(COMPILER) 08_GeometryRendering.c -w -lSDL2 -lSDL2_image -o 08_GeometryRendering.out
	./08_GeometryRendering.out
	rm 08_GeometryRendering.out

09: $(OBJS)
	$(COMPILER) 09_ViewPort.c -w -lSDL2 -lSDL2_image -o 09_ViewPort.out
	./09_ViewPort.out
	rm 09_ViewPort.out

10: $(OBJS)
	$(COMPILER) 10_color_keying.c -g3 -w -lSDL2 -lSDL2_image -o 10_color_keying.out
	./10_color_keying.out
	rm 10_color_keying.out


